src/AppBundle/Entity/Task.php
<?php

namespace AppBundle\Entity;

use AppBundle\Lib\Enumeration\IssueStatus;
use Doctrine\ORM\Mapping as ORM;

/**
 * Task
 *
 * @ORM\Table(name="task")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\TaskRepository")
 */
class Task
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255)
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(name="status", type="integer")
     */
    private $status = IssueStatus::JUST_CREATED;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     *
     * @return Task
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set status
     *
     * @param integer $status
     *
     * @return Task
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status
     *
     * @return integer
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @return string
     */
    public function getPrintTableStatus()
    {
        return IssueStatus::getALL()[$this->status];
    }

    /**
     * @return bool
     */
    public  function isJustCreated()
    {
        return $this->status == IssueStatus::JUST_CREATED;
    }

    /**
     * @return bool
     */
    public  function isDone()
    {
        return $this->status == IssueStatus::DONE;
    }

    /**
     * @return bool
     */
    public  function isInProgress()
    {
        return $this->status == IssueStatus::IN_PROGRESS;
    }
}

src/AppBundle/Controller/DefaultController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Task;
use AppBundle\Lib\Enumeration\IssueStatus;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;

class DefaultController extends Controller
{
    /**
     * @Route("/", name="homepage")
     * @Method({"GET","POST"})
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function indexAction(Request $request)
    {
        $tasks = $this->getDoctrine()
            ->getRepository(Task::class)
            ->findAll();

        $task = new Task();
        $form_builder = $this->createFormBuilder($task);
        $form_builder->add('title', TextType::class,[
            'label'=>'Добавит новую задачу',
            'required'=>true,
            'attr'=>[
                'placeholder'=>'Надо сделать'
            ]
        ]);
        $form_builder->add('save', SubmitType::class,[
            'label'=>"Добавить"
        ]);
        $form = $form_builder->getForm();
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $task = $form->getData();
            $em = $this->getDoctrine()->getManager();
            $em->persist($task);
            $em->flush();
            return $this->redirectToRoute("homepage");
        }
        return $this->render("@App/default/index.html.twig",[
            'form' => $form->createView(),
            'tasks'=>$tasks
        ]);
    }

    /**
     * @Route("/task/set_in_progress/{id}",name="taskSetInProgress")
     * @Method({"GET"})
     * @param $id integer
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function setInProgressAction(int $id)
    {
        $this->changeStatus($id,IssueStatus::IN_PROGRESS);
        return $this->redirectToRoute("homepage");
    }

    /**
     * @Route("/task/set_done/{id}",name="taskSetDone")
     * @Method({"GET"})
     * @param $id integer
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function setDoneAction(int $id)
    {
        $this->changeStatus($id,IssueStatus::DONE);
        return $this->redirectToRoute("homepage");
    }

    /**
     * @Route("/task/delete/{id}",name="taskDelete")
     * @Method({"GET"})
     * @param $id integer
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function deleteAction(int $id)
    {
        $task = $this->getDoctrine()
            ->getRepository(Task::class)
            ->find($id);

        if ($task){
            $em = $this->getDoctrine()->getManager();
            $em->remove($task);
            $em->flush();
        }
        return $this->redirectToRoute("homepage");
    }

    /**
     * @Route("/task/delete_done_all",name="taskDeleteDoneAll")
     * @Method({"GET"})
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function deleteDoneAllAction()
    {
        $tasks = $this->getDoctrine()
            ->getRepository(Task::class)
            ->findBy(['status' => IssueStatus::DONE]);
        if ($tasks){

            $em = $this->getDoctrine()->getManager();
            foreach ($tasks as $task){
                $em->remove($task);
            }
            $em->flush();
        }

        return $this->redirectToRoute("homepage");
    }

    /**
     * @param int $id
     * @param int $status
     */
    private function changeStatus(int $id,int $status)
    {
        $task = $this->getDoctrine()
            ->getRepository(Task::class)
            ->find($id);

        if ($task){
            $task->setStatus($status);
            $em = $this->getDoctrine()->getManager();
            $em->flush();
        }
    }
}

src/AppBundle/Resources/views/default/index.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
<style>
    .block-task{
        width: 600px;
        margin: 0 auto;
    }
    .block-task h1{
        font-family: sans-serif;
    }
    .block-task label{
        display: block;
        font-size: 24px;
        margin: 13px 0;
        font-family: sans-serif;
        font-weight: bold;
    }
    .block-task input{
        width: 95%;
        margin-bottom: 12px;
        height: 10px;
        padding: 10px;
        border: 1px solid black;
        border-radius: 14px;
        outline: none;
    }
    .block-task button{
        border: 1px solid black;
        padding: 5px;
        width: 160px;
        border-radius: 12px;
        color: white;
        background: #545454;
    }
    .block-task table,td,th {
        border: solid 1px #40bf17;
        border-collapse: collapse;
    }
    .block-task table{
        margin-bottom: 20px;
        width: 100%;
    }
    .block-task table thead{
        background: #69d845;
    }
    .block-task table thead th,td,table tbody th,td{
        padding:12px;
    }
    .block-task .remove-task,.start-task,.end-task {
        padding: 3px 7px;
        background: #e04343;
        display: inline-block;
        color: white;
        border-radius: 12px;
        text-decoration: none;
        font-size: 14px;
        font-family: sans-serif;
        margin-right: 5px;
    }
    .block-task .start-task {
        background: cornflowerblue;
    }
    .block-task .end-task{
        background: #b99118;
    }
</style>
{% endblock %}
{% block body %}
    <div class="block-task">
        <h1>Список Задач</h1>
        <table>
            <thead>
                <tr>
                    <th>Задача</th>
                    <th>Готовность</th>
                    <th>Действие</th>
                </tr>
            </thead>
            <tbody>
            {% for task in tasks %}
                <tr>
                    <td>{{ task.title }}</td>
                    <td>{{ task.printTableStatus }}</td>
                    <td>
                        {% if(task.justCreated) %}
                            <a class="start-task" href="{{ path('taskSetInProgress',{'id':task.id}) }}">Начать выполнение</a>
                        {% elseif(task.inProgress) %}
                            <a class="end-task" href="{{ path('taskSetDone',{'id':task.id}) }}">завершить выполнение</a>
                        {% endif %}
                        <a class="remove-task" href="{{ path('taskDelete',{'id':task.id}) }}">удалить</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="4">Нет задач</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

         <a class="remove-task" href="{{ path('taskDeleteDoneAll') }}">Удалить законченные задачи</a>

        {{ form_start(form) }}
        {{ form_widget(form) }}
        {{ form_end(form) }}
    </div>
{% endblock %}